from PySide6.QtCore import QObject

class IconDatabase(QObject):
    def __init__(self):
        super().__init__()

        self.icon_database = {
            self.tr("Default"): [
                "fa6s.arrow-left",
                "fa6s.arrow-right",
                "fa6s.arrow-rotate-right",
                "msc.layout-sidebar-left",
                "ri.menu-fill",
                "fa6s.clock-rotate-left",
                "mdi.arrow-right-bold-box",
                "fa6s.download",
                "ph.magnifying-glass-plus",
                "ph.magnifying-glass-minus",
            ],
            self.tr("General"): [
                "fa6s.angle-left",
                "fa6s.angle-right",
                "fa6s.angle-up",
                "fa6s.angle-down",
                "fa6s.arrow-rotate-left",
                "fa6s.arrow-pointer",
                "fa6s.arrows-rotate",
                "fa6s.circle-arrow-left",
                "fa6s.circle-arrow-right",
                "fa6s.circle-arrow-up",
                "fa6s.circle-arrow-down",
                "fa6s.circle-chevron-left",
                "fa6s.circle-chevron-right",
                "fa6s.circle-chevron-up",
                "fa6s.circle-chevron-down",
                "fa6s.circle-left",
                "fa6s.circle-right",
                "fa6s.circle-up",
                "fa6s.circle-down",
                "fa6s.circle",
                "fa6s.circle-dot",
            ],
            self.tr("People"): [
                "ei.adult",
                "ei.child",
                "ei.smiley",
                "ei.user",
                "ei.wheelchair",
                "ei.hand-left",
                "ei.hand-right",
                "ei.hand-down",
                "ei.hand-up",
                "fa6s.face-angry",
                "fa6s.face-dizzy",
                "fa6s.face-flushed",
                "fa6s.face-frown",
                "fa6s.face-frown-open",
                "fa6s.face-grimace",
                "fa6s.face-grin",
                "fa6s.face-grin-beam",
                "ei.person",
                "ei.torso",
                "ei.universal-access",
            ],
            self.tr("Technology"): [
                "fa6s.comment",
                "fa6s.comment-dots",
                "fa6s.comment-medical",
                "fa6s.comments",
                "fa6s.computer",
                "fa6s.computer-mouse",
                "fa6s.desktop",
                "fa6s.database",
                "fa6s.display",
                "fa6s.file",
                "fa6s.file-arrow-down",
                "fa6s.file-arrow-up",
                "fa6s.folder",
                "fa6s.folder-tree",
                "fa6s.gear",
                "fa6s.mobile-screen",
                "fa6s.mobile-screen-button",
                "fa6s.mobile-retro",
                "fa6s.power-off",
                "fa6s.print",
                "fa6s.radio",
            ],
            self.tr("Food and Drinks"): [
                "fa6s.bone",
                "fa6s.apple-whole",
                "fa6s.burger",
                "fa6s.bread-slice",
            ],
            self.tr("Brands / Companies"): [
                "ei.youtube",
                "ei.wordpress",
                "ei.vkontakte",
                "ei.vimeo",
                "ei.w3c",
                "ei.twitter",
                "ei.tumblr",
                "ei.viadeo",
                "ei.stumbleupon",
                "ei.slideshare",
                "ei.spotify",
                "ei.stackoverflow",
                "ei.soundcloud",
                "ei.skype",
                "ei.reddit",
                "ei.redux",
                "ei.livejournal",
                "ei.instagram",
                "ei.github",
                "ei.foursquare",
                "ei.friendfeed",
                "ei.facebook",
                "ei.blogger",
                "ei.behance",
                "ei.myspace",
                "fa5b.amazon",
                "fa5b.app-store",
            ],
            self.tr("Miscellaneous"): [
                "fa6s.circle-radiation",
                "fa6s.graduation-cap",
                "fa6s.hammer",
                "fa5s.adjust",
                "fa5s.anchor",
                "fa6s.dna",
                "fa6s.biohazard",
            ]
        }